Update italian.yml
koheiw/newsmap pull request #50
Opened 2022-01-13 11:09 UTC by giucarny

Removed 'Città di Ho Chi Minh' and added 'Saigon' (#47).

2022-01-13 12:23 UTC, koheiw commented on dict/italian.yml
> +    'RE': [Riunione, Saint-Denis]                                                              #inhabitants' Italian official name is missing
Can you explain what is "inhabitant's official name"?

2022-02-12 00:59 UTC, koheiw requested changes
Let's delete the comments on the official names because it is not only about Italian.

2022-02-12 15:15 UTC, giucarny commented
https://github.com/koheiw/newsmap/pull/50#issuecomment-1036912070
Next time I will follow the workflow suggested by you. In the meantime, I believe that this PR could be merged, otherwise let me know and I'll create another one.

2022-02-12 22:52 UTC, koheiw approved these changes

2022-02-12 22:52 UTC, merged

2022-02-12 22:53 UTC, koheiw commented
@giucarny thanks. I will remove the comments myself.